version: "3"
services:
  hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  cucumber-testcase:
    image: cucumbertestimage
    depends_on:
      - hub
    environment:
      - browser=Chrome
    volumes:
      - ./executionreport:/home/seleniumbddtestframework/target  

